openapi: 3.0.4
info:
  title: NOMBRE APP - OpenAPI 3.0
  description: BREVE DESCRIPCION
  termsOfService: https://swagger.io/terms/
  contact:
    email: EMAIL@EMAIL.COM
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
servers:
  - url: URL
paths:
  /ejemplo:
    get:
      summary: RESUMEN
      responses:
        200:
          description: DESCRIPCION
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: EJEMPLO
